import { NextResponse } from 'next/server'

// Real skills installed in this OpenClaw instance
const SKILLS = [
  {
    id: 'clawsec-suite',
    name: 'ClawSec Suite',
    version: '0.1.4',
    enabled: true,
    status: 'active',
    description: 'Security advisory monitoring + cryptographic signature verification + approval-gated malicious-skill response.',
    source: 'clawhub',
    capabilities: ['advisory-feed', 'signature-verification', 'malicious-skill-response', 'guided-setup'],
    lastRun: null,
  },
  {
    id: 'soul-guardian',
    name: 'Soul Guardian',
    version: '0.0.2',
    enabled: true,
    status: 'active',
    description: 'Drift detection + baseline integrity guard for agent workspace files with automatic alerting support.',
    source: 'clawhub',
    capabilities: ['drift-detection', 'baseline-integrity', 'alerting', 'workspace-guard'],
    lastRun: null,
  },
  {
    id: 'openclaw-audit-watchdog',
    name: 'Audit Watchdog',
    version: '0.1.1',
    enabled: true,
    status: 'active',
    description: 'Automated daily security audits for OpenClaw agents with email reporting. Runs deep audits and sends formatted reports.',
    source: 'clawhub',
    capabilities: ['daily-audits', 'email-reporting', 'deep-scan', 'compliance-report'],
    lastRun: null,
  },
  {
    id: 'searxng-local',
    name: 'SearXNG Local',
    version: '1.0.0',
    enabled: true,
    status: 'active',
    description: 'Web search via a locally-deployed SearXNG meta-search engine.',
    source: 'openclaw-managed',
    capabilities: ['web-search', 'privacy-routing', 'result-filtering'],
    lastRun: null,
  },
  {
    id: 'acp-router',
    name: 'ACP Router',
    version: '1.0.0',
    enabled: true,
    status: 'active',
    description: 'Route plain-language requests to Claude Code, Codex, OpenCode, Gemini CLI, or ACP harness work.',
    source: 'openclaw-extra',
    capabilities: ['claude-code', 'codex', 'gemini-cli', 'acp-sessions'],
    lastRun: null,
  },
  {
    id: 'one-drive',
    name: 'OneDrive',
    version: '1.0.3',
    enabled: true,
    status: 'active',
    description: 'OneDrive file storage via Maton gateway integration.',
    source: 'clawhub',
    capabilities: ['file-storage', 'file-retrieval', 'folder-management'],
    lastRun: null,
  },
  {
    id: 'coding-agent',
    name: 'Coding Agent',
    version: '1.0.0',
    enabled: true,
    status: 'active',
    description: 'Full coding agent with Claude Code integration for complex development tasks.',
    source: 'openclaw',
    capabilities: ['code-generation', 'pr-creation', 'refactoring', 'debugging'],
    lastRun: null,
  },
  {
    id: 'github',
    name: 'GitHub',
    version: '1.0.0',
    enabled: true,
    status: 'active',
    description: 'GitHub API integration for repository management, PRs, issues, and actions.',
    source: 'openclaw',
    capabilities: ['repos', 'pull-requests', 'issues', 'actions'],
    lastRun: null,
  },
  {
    id: 'weather',
    name: 'Weather',
    version: '1.0.0',
    enabled: true,
    status: 'active',
    description: 'Weather checking via wttr.in for any location.',
    source: 'openclaw',
    capabilities: ['current-weather', 'forecast'],
    lastRun: null,
  },
]

export async function GET() {
  return NextResponse.json(SKILLS)
}
